apiVersion: v1
kind: Service
metadata:
  namespace: portfolio
  name: my-portfolio-service
spec:
  type: ClusterIP
  selector:
    app: my-portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
